import './js/api-service';
import './js/start-loading';
import './js/countrySearch';
import './js/scroll-top-btn';
import './js/team';
import './js/modal-open';
import './js/modalRender';
// import './js/modal-infa';
import './sass/main.scss';
// import './js/modalFromApi main';
import './js/preloader';
